### ISSUE TITLE
can't run ganache

### ISSUE THREAD

**Issue by gaemltim** [trufflesuite/ganache-ui#2094]
Error: corda bootstrapper child process exited with code 1.

Stderr:
#### Error while generating node info file C:\Users\pc\AppData\Roaming\Ganache\workspaces\Quickstart\chaindata\partyc\logs ####
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 59768832 bytes for Failed to commit area from 0x00000000ee300000 to 0x00000000f1c00000 of length 59768832.
# An error report file with more information is saved as:
# C:\Users\pc\AppData\Roaming\Ganache\workspaces\Quickstart\chaindata\partyc\hs_err_pid22616.log
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000ee300000, 59768832, 0) failed; error='ҳ���ļ�̫С���޷���ɲ�����' (DOS error/errno=1455)
#### Error while generating node info file C:\Users\pc\AppData\Roaming\Ganache\workspaces\Quickstart\chaindata\partya\logs ####
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 134217728 bytes for Failed to commit area from 0x00000000e0000000 to 0x00000000e8000000 of length 134217728.
# An error report file with more information is saved as:
# C:\Users\pc\AppData\Roaming\Ganache\workspaces\Quickstart\chaindata\partya\hs_err_pid7616.log
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000e0000000, 134217728, 0) failed; error='ҳ���ļ�̫С���޷���ɲ�����' (DOS error/errno=1455)
CAPSULE: Client connection failed.
CAPSULE EXCEPTION: Accept timed out while processing null null: null (for stack trace, run with -Dcapsule.log=verbose)
#### Error while generating node info file C:\Users\pc\AppData\Roaming\Ganache\workspaces\Quickstart\chaindata\partyb\logs ####
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 134217728 bytes for Failed to commit area from 0x00000000e0000000 to 0x00000000e8000000 of length 134217728.
# An error report file with more information is saved as:
# C:\Users\pc\AppData\Roaming\Ganache\workspaces\Quickstart\chaindata\partyb\hs_err_pid4568.log
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000e0000000, 134217728, 0) failed; error='ҳ���ļ�̫С���޷���ɲ�����' (DOS error/errno=1455)
CAPSULE: Client connection failed.
CAPSULE EXCEPTION: Accept timed out while processing null null: null (for stack trace, run with -Dcapsule.log=verbose)
#### Error while generating node info file C:\Users\pc\AppData\Roaming\Ganache\workspaces\Quickstart\chaindata\notary\logs ####
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 134217728 bytes for Failed to commit area from 0x00000000e0000000 to 0x00000000e8000000 of length 134217728.
# An error report file with more information is saved as:
# C:\Users\pc\AppData\Roaming\Ganache\workspaces\Quickstart\chaindata\notary\hs_err_pid23392.log
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000e0000000, 134217728, 0) failed; error='ҳ���ļ�̫С���޷���ɲ�����' (DOS error/errno=1455)
CAPSULE: Client connection failed.
CAPSULE EXCEPTION: Accept timed out while processing null null: null (for stack trace, run with -Dcapsule.log=verbose)
Error while generating node info file. Please check the logs in C:\Users\pc\AppData\Roaming\Ganache\workspaces\Quickstart\chaindata\partyc\logs.

Stdout:
2020-10-30 18:05:58,370 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2020-10-30 18:05:58,372 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
Bootstrapping local test network in C:\Users\pc\AppData\Roaming\Ganache\workspaces\Quickstart\chaindata
Generating node directory for notary
Generating node directory for partya
Generating node directory for partyb
Generating node directory for partyc
Nodes found in the following sub-directories: [notary, partya, partyb, partyc]
Found the following CorDapps: []
Waiting for all nodes to generate their node-info files...

Error:

config:{"env":{"PATH":"C:\\Users\\pc\\AppData\\Roaming\\Ganache\\extras\\OpenJDK8U-jre_x64_windows_hotspot_8u232b09\\bin","CAPSULE_CACHE_DIR":"./capsule"},"cwd":"C:\\Users\\pc\\AppData\\Roaming\\Ganache\\workspaces\\Quickstart\\chaindata"}
    at CordaBootstrap.handleClose (C:\Program Files\Ganache\resources\app.asar\webpack:\src\integrations\corda\main\utils\network\bootstrap.js:120:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

**Comment by davidmurdoch** [comment]
Hmm, haven't seen this issue before. How much memory do you have available on your system?
