### ISSUE TITLE
Contracts Storage display error

### ISSUE THREAD

**Issue by glazec** [trufflesuite/ganache-ui#2164]
![image](https://user-images.githubusercontent.com/22890026/100585295-31693000-32a2-11eb-94cc-3ebdad527fa0.png)

## Expected Behavior
There should be some data in balances mapping.

## Current Behavior
No items in balances are displayed

## Steps to Reproduce (for bugs)

1. truffle unbox metacoin
2. set up local network via ganache
3. deploy contracts

## Context
I cannot find a way to inspect the storage of the contract.

## Your Environment

* PLATFORM: win32
* GANACHE VERSION: 2.5.4
* Node version: 14.15.1
* Operating System and version: Winodows10
* Truffle version:5.15

**Comment by ValentinFFM** [comment]
Mapping is also not displayed in Ganache on macOS 11.1. Here further more the application seems to crash if you click on a transaction, where an instance of mapping was created or used. Ganache returns the following error code: 

TypeError: Cannot read property 'stack' of undefined
    at IpcMainImpl.<anonymous> (/webpack:/src/integrations/ethereum/index.js:96:31)

**Comment by vellarod** [comment]
any updates on this?
