### ISSUE TITLE
System Error when running Ganache 2.5.4 on linux

### ISSUE THREAD

**Issue by negishubham3503** [trufflesuite/ganache-ui#2230]
I deployed my contract using truffle migrate then switched to ganache and clicked on the deployed contract tab. Just after this I got an error mentioned below.

PLATFORM: linux
GANACHE VERSION: 2.5.4

EXCEPTION:
```
TypeError: Cannot read property 'stack' of undefined
    at IpcMainImpl.<anonymous> (/webpack:/src/integrations/ethereum/index.js:76:29)
```

**Comment by jsgphd** [comment]
me too... The contract works the first time I deploy on a clean workspace, but then after I migrate with --reset a few times, I get this same error.
