### ISSUE TITLE
The hostname is not local address; only use hostnames/IPs associated with this machine

### ISSUE THREAD

**Issue by Neharoy2022** [trufflesuite/ganache-ui#4760]
Unable to access the test network as the above error pops up stating the host name as 0.0.0.0 all interfaces.

unable to restart or amend the host address please help.

**Comment by Neharoy2022** [comment]
@MicaiahReid and @davidmurdoch , Issue resolved: Step 1. on Windows, close Ganache app.  Step 2. Then search for %appdata% and then delete Ganache folder. Step 3.Restart ganache and it should work as before.

Note: The problem occurs only when I change the server to vEthernet (WSL).

**Comment by IceCreamSandwich98** [comment]
Had the same issue. thanks
