### ISSUE TITLE
MacOS version 2.7.0 new code signature

### ISSUE THREAD

**Issue by suschizu** [trufflesuite/ganache-ui#5286]
Has the code signature changed in version 2.7.0?

EXPECTED Timothy Coulter (58RKXWC272) 
FOUND ConsenSys AG (48XVW22RCG)

## Your Environment

* Ganache version: 2.7.0
* Node version:
* Operating System and version: 12.6.3
#

**Comment by davidmurdoch** [comment]
Yes. This is expected for this release. Timothy Coulter no longer works here so we had to change certificates.

We'll update the release notes tomorrow. Thanks for raising this issue. I'll pin it to help others that may stumble on this.

**Comment by suschizu** [comment]
great - thanks
