### ISSUE TITLE
Account Lock/unlock buttons?

### ISSUE THREAD

**Issue by johnmcdowall** [trufflesuite/ganache-ui#61]
Possible WONTFIX

**Comment by melnikaite** [comment]
I'd like to have this feature.

**Comment by wimdetr** [comment]
Any update on this? Would love to see this implemented in the gui. For now, does:

`$ ganache --unlock 0,1 & 
`
work?

**Comment by seesemichaelj** [comment]
We've deliberated on this and decided it's lower priority; we haven't been able to figure out the appropriate UX for this feature, but we still think this could be a beneficial feature.

**Comment by seesemichaelj** [comment]
@wimdetr if you want to do a more advanced feature, you can add ganache-core options in the `Settings` file:
- MacOS: `~/Library/Application\ Support/Ganache/Settings`
- Windows: `%APPDATA%\Ganache\Settings`
- Linux: either `$XDG_CONFIG_HOME/Ganache/Settings` or `~/.config/Ganache/Settings`
